zuul:
  routes:
    loginAndregister-server: /login
    loginAndregister-server: /register
server:
  port: 8000
spring:
  application:
    name: gateway-server
eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8002/eureka/



